#!/usr/bin/env bash
set -euo pipefail

# wt-setup.sh — Worktree セットアップスクリプト
# SKILL.md から呼び出される。判定ロジックをスクリプトに集約し、
# LLMの解釈ミスによる事故を防ぐ。
#
# サブコマンド:
#   --print-default-worktreeinclude   既定の .worktreeinclude を stdout に出す

#=== 既定の .worktreeinclude（issue #55） ===
#
# LLM に毎回書かせるとテンプレが揺れるため、既定パターンはスクリプト側に置く。
# SKILL.md の Step 2 はこの出力をそのまま書き出し、repo 固有パターンだけを追記する。

print_default_worktreeinclude() {
  cat <<'EOF'
# Auto-generated by wt-setup
# gitignore されたファイルのうち、worktree にコピーすべきもの。
#
# `!` で始まる行は除外パターン（コピーしない）。バックアップ・エディタ残骸
# （*.bak / *.bak-* / *.old / *.orig / *~ など）はスクリプト側で常に除外されるため
# ここに書く必要はない。repo 固有の除外だけを `!` 行で足す。
#
# .vercel は既定では配布しない（必要な repo だけがオプトインで下の行を有効化する）。
#   `vercel link` / `vercel env pull` が .vercel/.env.production.local を作ると、
#   本番環境変数一式がすべての worktree に複製されるため（issue #55）。
# .vercel/*

# Environment files
.env
.env.*

# Local config
*.local.json
*.local.md
EOF
}

if [ "${1:-}" = "--print-default-worktreeinclude" ]; then
  print_default_worktreeinclude
  exit 0
fi

#=== Step 1: 環境判定 ===

# worktree内かどうか判定（判定は TOPLEVEL と MAIN_REPO の一致で行う）
TOPLEVEL=$(git rev-parse --show-toplevel 2>/dev/null)
MAIN_REPO=$(git worktree list | head -1 | awk '{print $1}')

if [ "$TOPLEVEL" = "$MAIN_REPO" ]; then
  echo "ERROR: メインリポジトリ内で実行されています。worktree内で実行してください。"
  exit 1
fi

echo "worktree: $TOPLEVEL"
echo "main repo: $MAIN_REPO"

#=== Step 2: .worktreeinclude のファイルコピー ===

# 既定の除外パターン（issue #55）。
# `.env.*` のようなワイルドカードは `.env.local.bak-stripe-migration` のような
# **バックアップ**にも一致し、ローテート前の本番値が全 worktree に焼き付いた
# （Uranai で実証）。既存 10 repo の `.worktreeinclude` を書き換えなくても
# 巻き込みが止まるよう、除外はスクリプト側の既定として持つ。
# 対象は「バックアップ・エディタ残骸」という再生成不要のカテゴリに限定する
# （`.env.development.local` のような正当な派生ファイルは除外しない）。
WT_DEFAULT_EXCLUDES=(
  '*.bak' '*.bak-*' '*.bak.*' '*.backup' '*-backup' '*.old' '*.orig'
  '*.save' '*.rej' '*~' '*.swp' '*.tmp'
  '*.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'  # .env.local.20260101 形式の退避
)

# $1: `./` 付きの相対パス。除外対象なら 0 を返す。
# 既定除外はベース名に対して、`!` 行のユーザー除外はベース名とパスの両方に対して照合する。
wt_is_excluded() {
  local path="${1#./}" base pat
  base="$(basename "$path")"
  for pat in "${WT_DEFAULT_EXCLUDES[@]}"; do
    # shellcheck disable=SC2053
    [[ "$base" == $pat ]] && return 0
  done
  for pat in "${USER_EXCLUDES[@]:-}"; do
    [ -z "$pat" ] && continue
    # shellcheck disable=SC2053
    [[ "$base" == $pat || "$path" == $pat ]] && return 0
  done
  return 1
}

# 本番値ガード（issue #55）。コピー対象の中身に本番クレデンシャルらしき
# パターンがあれば**警告して続行**する。スキップにしないのは、開発中に本番の
# Stripe キーや Supabase service_role を意図して使う正当な用途（本番データの
# 調査・移行スクリプトの検証）を静かに壊す方が危険なため。検出結果は
# 「どのファイルに何の種類が入っていたか」だけを出し、**値は絶対に出力しない**
# （セッションログに秘密が残るのを防ぐ）。
# $1: 走査するファイルの絶対パス。検出したラベルを 1 行ずつ stdout に返す。
wt_scan_production_values() {
  local file="$1" label pattern
  while IFS='|' read -r label pattern; do
    [ -z "$label" ] && continue
    if LC_ALL=C grep -Eqs -- "$pattern" "$file"; then
      echo "$label"
    fi
  done <<'PATTERNS'
Stripe 本番シークレット (sk_live_/rk_live_)|(sk|rk)_live_[A-Za-z0-9]{8}
Supabase service_role キー|service_role|SERVICE_ROLE|c2VydmljZV9yb2xl|NlcnZpY2Vfcm9s|zZXJ2aWNlX3JvbG
本番 DB ホスト|db\.[a-z0-9]{16,}\.supabase\.co|\.pooler\.supabase\.com|\.rds\.amazonaws\.com|\.neon\.tech
AWS アクセスキー|(AKIA|ASIA)[0-9A-Z]{16}
PATTERNS
}

if [ -f .worktreeinclude ]; then
  echo ""
  echo "=== .worktreeinclude: 既存 ==="
  COPIED=0
  SKIPPED=0
  EXCLUDED=0
  WARNED=0
  # `!pattern` 行 = repo 固有の除外パターン。先に全部集めてからコピーに入る。
  USER_EXCLUDES=()
  while IFS= read -r line; do
    [[ "$line" =~ ^! ]] && USER_EXCLUDES+=("${line#!}")
  done < .worktreeinclude
  while IFS= read -r pattern; do
    [[ "$pattern" =~ ^#.*$ || -z "$pattern" || "$pattern" =~ ^! ]] && continue
    # find -path のグロブ挙動（実挙動確認済み・意図の明文化）:
    #   `find . -path "./$pattern"` は $pattern を 1 個のパス glob として扱う。
    #   `.env` / `.env.*` / `*.local.json` / `*.local.md` のような 1 階層パターンは
    #   リポジトリ直下のファイルのみに一致し、サブディレクトリ配下（例: config/foo.env.local）
    #   には一致しない。.worktreeinclude の既定パターンはいずれもリポジトリ直下想定のため、
    #   この直下限定挙動が意図通り（サブディレクトリまで拾いたい場合は "./**/$pattern" を
    #   別パターンとして追記する運用にする）。
    while IFS= read -r file; do
      # gitignore されたファイルだけをコピーする（issue #80）。
      # .worktreeinclude の契約は「gitignore されたファイルのうち worktree に
      # コピーすべきもの」だが、`.env.*` のような glob は `.env.local.example` の
      # ような**追跡済み**ファイルにも一致する。メインリポの checkout が古いと、
      # その古い内容が worktree の追跡ファイルを上書きし、「誰も触っていないのに
      # 行が消えた」幽霊差分になる（実例: suimei の .env.local.example から
      # SM_LP_ORIGIN が消えた件）。判定はメインリポ側で行う。
      # ls-files も見るのは、`.gitignore` に載っているのに force-add されて
      # 追跡されているファイルが check-ignore では「ignore 済み」と出るため。
      # 上書きすると幽霊差分になる点は同じなので、どちらか一方でも該当したら飛ばす。
      # check-ignore が異常終了（128 等）した場合も「ignore ではない」側に倒れて
      # スキップされる ＝ 検査不能ならコピーしない fail-closed になっている。
      if git -C "$MAIN_REPO" ls-files --error-unmatch "$file" >/dev/null 2>&1 \
        || ! git -C "$MAIN_REPO" check-ignore -q "$file"; then
        echo "  skipped (tracked): $file"
        SKIPPED=$((SKIPPED + 1))
        continue
      fi
      # バックアップ・エディタ残骸は配布しない（issue #55）
      if wt_is_excluded "$file"; then
        echo "  skipped (excluded): $file"
        EXCLUDED=$((EXCLUDED + 1))
        continue
      fi
      # 本番値ガード: 検出しても止めず、警告だけ出してコピーは続ける
      while IFS= read -r label; do
        [ -z "$label" ] && continue
        echo "  WARNING: 本番値の疑い: $file — $label"
        WARNED=$((WARNED + 1))
      done < <(wt_scan_production_values "$MAIN_REPO/$file")
      dir=$(dirname "$file")
      mkdir -p "$dir"
      cp "$MAIN_REPO/$file" "$file" 2>/dev/null && echo "  copied: $file" && COPIED=$((COPIED + 1))
    done < <(cd "$MAIN_REPO" && find . -path "./$pattern" -type f 2>/dev/null)
  done < .worktreeinclude
  echo "  total: $COPIED files copied, $SKIPPED skipped (tracked), $EXCLUDED skipped (excluded), $WARNED warnings"
  if [ "$WARNED" -gt 0 ]; then
    echo "  NOTE: 本番値の疑いがあるファイルもコピー済み（警告のみ・値は非表示）。"
    echo "        意図しない配布なら .worktreeinclude に \`!<pattern>\` を足すか、メインリポ側の値を確認する。"
  fi
else
  echo ""
  echo "=== .worktreeinclude: なし（SKILL.mdの手順で生成してください） ==="
  echo "  既定テンプレート: bash \"\$0\" --print-default-worktreeinclude > .worktreeinclude"
fi

#=== Step 3: .claude/ の共有 ===

echo ""
if [ -L .claude ]; then
  echo "=== .claude/: 既にシンボリンク → スキップ ==="
  echo "  WARNING: .claude/ が丸ごとシンボリンクになっています。サブディレクトリ単位のリンクが推奨です。"
elif git ls-files --error-unmatch .claude/ &>/dev/null 2>&1; then
  echo "=== .claude/: git追跡済み → symlinkスキップ（既にworktreeに存在） ==="
else
  echo "=== .claude/: 未追跡 → symlinkを作成 ==="
  mkdir -p .claude

  for subdir in skills commands rules; do
    if [ -d "$MAIN_REPO/.claude/$subdir" ]; then
      ln -sfn "$MAIN_REPO/.claude/$subdir" ".claude/$subdir"
      echo "  symlink: .claude/$subdir"
    fi
  done

  # settings.local.json の symlink 是非（実挙動確認済み・意図の明文化）:
  #   settings.local.json はマシンローカルの権限許可（permissions.allow 等）を含みうる。
  #   worktree にこれを symlink すると、メインリポの許可設定が worktree にも効く。
  #   同一マシン・同一ユーザーの worktree では、毎回許可し直さずに済むためむしろ望ましい。
  #   よって symlink 対象として現状維持する（worktree 固有の設定で上書きしたい特殊ケースが
  #   出た場合のみ、この file ループから settings.local.json を外す）。
  for file in settings.json settings.local.json; do
    if [ -f "$MAIN_REPO/.claude/$file" ]; then
      ln -sfn "$MAIN_REPO/.claude/$file" ".claude/$file"
      echo "  symlink: .claude/$file"
    fi
  done
fi

#=== Step 4: 依存チェック ===

echo ""
echo "=== 依存状況 ==="
if [ -f package.json ] && [ ! -d node_modules ]; then
  echo "  node_modules なし → npm install が必要"
  echo "  NEEDS_NPM_INSTALL=true"
elif [ -f package.json ]; then
  echo "  node_modules あり"
fi

if [ -f Gemfile ] && [ ! -d .bundle ] && ! command -v bundle &>/dev/null; then
  echo "  bundle なし → bundle install が必要"
fi

echo ""
echo "=== wt-setup 完了 ==="
